package lumia.tracker.util

object StreakNotifications {
    val motivational = listOf(
        "You're doing great! Keep up the good work.",
        "Another step forward. Amazing job!",
        "Consistency is key, and you're unlocking it.",
        "Awesome! You've crushed today's goals.",
        "Your dedication is inspiring. Keep going!",
        "Small steps every day lead to big results.",
        "You are unstoppable! Great work today.",
        "Look at you go! The streak continues.",
        "You're building a beautiful habit.",
        "One more day closer to your dreams.",
        "Excellent effort today. Rest well!",
        "You've earned this victory. Be proud!",
        "Setting the bar higher every single day.",
        "Progress, not perfection. And you made progress!",
        "You are on fire! Keep the momentum alive.",
        "Fantastic work! You're really on a roll.",
        "It's paying off. Keep your eyes on the prize.",
        "Consistency looks incredibly good on you.",
        "Believe in yourself. Today proves you can do it.",
        "Another day, another win. Outstanding!",
        "Building momentum, day by day. Great job!",
        "Your hard work is stacking up to greatness.",
        "The journey is long, but your stride is strong.",
        "Be proud of showing up today!",
        "Every effort counts. You're doing amazing!",
        "You're creating an awesome streak right now.",
        "Good habits are forming. Excellent!",
        "Keep that flame burning bright!",
        "Focus and dedication win the race. You got this.",
        "The hardest part is starting. You finished!",
        "Your future self is thanking you today.",
        "Today's effort is tomorrow's success.",
        "Keep climbing, you are doing wonderfully.",
        "Stellar work today! Enjoy the feeling of accomplishment.",
        "It’s all about consistency, and you nailed it today!",
        "Way to go! You’re getting better every day.",
        "Don't stop now, you're doing phenomenally well!",
        "Awesome dedication. Keep it up!",
        "You turned your goals into reality today.",
        "Brilliant work! You should be very proud."
    )

    val aggressive = listOf(
        "Do not break the streak. I am watching you.",
        "Good job. Now do it again tomorrow. No excuses.",
        "You did what was expected. Nothing more. Keep going.",
        "You survived today. Tomorrow will be harder.",
        "Keep pushing, or someone else will take your spot.",
        "The streak lives. Do not let it die on your watch.",
        "You met the minimum requirement. Barely.",
        "Don't get comfortable. The real work is yet to come.",
        "Complacency is the enemy. Stay sharp.",
        "You did it today. Let's see if you can do it tomorrow.",
        "Excuses don't build streaks. Actions do. Good action.",
        "If you stop now, all of this was for nothing.",
        "Keep the streak alive, or face the consequences of failure.",
        "Victory today. War tomorrow. Prepare yourself.",
        "Do you want to be average? Then keep doing this. If you want to be great, do more.",
        "Streak extended. But you can push harder.",
        "I'll tolerate today's effort. But raise the bar tomorrow.",
        "Don't be weak. Keep the flame alive.",
        "Your competitors are resting. You shouldn't be.",
        "Pain is temporary. The streak is forever.",
        "You showed up. Now show out tomorrow.",
        "Only the disciplined survive. Stay disciplined.",
        "Do not dare break this chain.",
        "You are building a weapon. Keep forging.",
        "No days off in the pursuit of greatness.",
        "Mediocrity is knocking. Keep the door closed.",
        "You call that hard work? Do better tomorrow.",
        "The fire is burning, don't let it go out.",
        "Today was just a warm-up for tomorrow.",
        "Don't look back. Just keep moving forward, aggressively.",
        "The streak demands blood, sweat, and focus.",
        "Sleep when the streak is safe. Which is never.",
        "You want success? This is the price. Pay up again tomorrow.",
        "Keep your foot on the gas. No braking allowed.",
        "The streak is your master now. Obey it.",
        "Good. Now go harder.",
        "Prove you're not a fluke. Do it again.",
        "Stop celebrating. The job isn't done.",
        "If you quit, you're just like everyone else.",
        "Maintain the streak. At all costs."
    )
}
