package lumia.tracker.util

object StreakNotifications {
    val motivational = listOf(
        "You're doing great! Keep up the good work.",
        "Another step forward. Amazing job!",
        "Consistency is key, and you're building it every day.",
        "Awesome! You've achieved today's streak goal.",
        "Your dedication is inspiring. Keep going!",
        "Small steps every day lead to big results.",
        "Great work today! The streak continues.",
        "Look at you go! Keeping the habit strong.",
        "You're building a healthy, lasting habit.",
        "One more day closer to your goals.",
        "Excellent effort today. Enjoy the accomplishment!",
        "You've earned this progress. Be proud!",
        "Setting the bar higher every single day.",
        "Progress, not perfection. You made meaningful progress today!",
        "Building steady momentum, day by day. Great job!",
        "Fantastic work! You're really on a roll.",
        "Every bit of effort pays off. Keep your eyes on the prize.",
        "Consistency looks great on you.",
        "Believe in yourself. Today proves your dedication.",
        "Another day, another win. Outstanding!",
        "Your hard work is compounding into real progress.",
        "The journey is long, but your stride is steady and strong.",
        "Be proud of showing up and delivering today!",
        "Every effort counts. You're doing wonderful work!",
        "You're building an incredible streak right now.",
        "Good habits are taking root. Keep it up!",
        "Keep that momentum alive and thriving!",
        "Focus and dedication win the race. You've got this.",
        "You showed up and finished today strong.",
        "Your future self will thank you for today's effort.",
        "Today's effort sets up tomorrow's success.",
        "Keep climbing — you're doing wonderfully.",
        "Stellar work today! Enjoy the feeling of accomplishment.",
        "It's all about consistency, and you nailed it today!",
        "Way to go! You're improving every single day.",
        "Stay steady, you're doing phenomenally well!",
        "Great dedication. Keep that streak going!",
        "You turned your goals into reality today.",
        "Brilliant work! You should be very proud of your consistency."
    )

    val aggressive = listOf(
        "Goal accomplished. Reset and bring the same discipline tomorrow.",
        "Execution over excuses. Good work handling today.",
        "Standards remain high. Keep this momentum rolling.",
        "The streak lives. Keep showing up every single day.",
        "Consistency is non-negotiable. See you back here tomorrow.",
        "Discipline today creates freedom tomorrow. Don't let up.",
        "Another day handled. Stay hungry, stay focused.",
        "You put the work in today. Keep raising the bar.",
        "Great execution today. Come back ready for tomorrow.",
        "No shortcuts, no excuses. Solid work today.",
        "Discipline is doing what needs to be done. Keep it moving.",
        "Momentum is built day by day. Stay locked in.",
        "You delivered today. Keep that exact same drive alive.",
        "Every single day counts. Keep stacking these wins.",
        "Hard work compounds over time. Stay relentless.",
        "Solid follow-through today. Keep pushing your limits.",
        "Focus on the process. The results will take care of themselves.",
        "Job done for today. Don't lose focus tomorrow.",
        "Great discipline today. Keep that fire burning.",
        "You showed up and executed. Maintain the standard.",
        "Keep your foot on the gas. Momentum is everything.",
        "One step closer to mastery. Keep grinding.",
        "Dedication isn't a one-time effort. Stay consistent.",
        "Consistency separates the best from the rest. Good work.",
        "High standards require daily commitment. Good follow-through.",
        "Locked in today. Bring that same intensity tomorrow.",
        "Streaks aren't given, they're earned. You earned today.",
        "Keep building. Strong habits withstand any challenge.",
        "You handled business today. Keep your eyes forward.",
        "Never settle for average. Keep moving forward with purpose.",
        "Great focus today. Come back ready to do it again.",
        "Action speaks louder than words. Solid effort today.",
        "Stay sharp. The work you do today builds tomorrow's wins.",
        "Showed up, worked hard, got it done. Repeat tomorrow.",
        "Discipline beats motivation every time. Great job today."
    )
}
