name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Remove invalid macOS Icon files
      run: find app/src/main/res -type f -name "Icon*" -delete

    - name: Generate debug.keystore
      run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

    - name: Build Debug APK
      run: gradle assembleDebug

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Lumia.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Lumia
        path: app/build/outputs/apk/debug/Lumia.apk
